.enable_db: &enable_db false

app:
  enabled: true
  image:
    tag: 0.12.0
  secretStringData:
    MONGO_DB_NAME: "react"
    SAMPLE_SECRET: "SAMPLE_SECRET_ENV_VAR"
  configMapData:
    DEV_DATABASE_URL_ORIGIN: "mongodb://react-db:27017"
    ENABLE_DB:               *enable_db
db:
  enabled: *enable_db
